name: Generate Doxygen Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: Run Doxygen
      run: |
        cd laboratories/cicd-documentation
        # Dacă nu există deja un Doxyfile, generăm unul default rapid
        if [ ! -f Doxyfile ]; then doxygen -g; fi
        doxygen Doxyfile

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v3
      with:
        name: doxygen-docs
        path: laboratories/cicd-documentation/html/